const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const defaults = {
  TARGET_URL: 'http://localhost:9000',
  PROXY_PORT: '4000',
  REDIS_URL: 'redis://localhost:6379',
  POSTGRES_URL: 'postgresql://sideris:sideris@localhost:5432/sideris'
};

const questions = [
  {
    key: 'TARGET_URL',
    query: `1. What is the URL of your existing website? [e.g., http://localhost:9000] (default: ${defaults.TARGET_URL}): `
  },
  {
    key: 'PROXY_PORT',
    query: `2. Which port should SIDERIS listen on? (default: ${defaults.PROXY_PORT}): `
  },
  {
    key: 'REDIS_URL',
    query: `3. What is your Redis URL? (default: ${defaults.REDIS_URL}): `
  },
  {
    key: 'POSTGRES_URL',
    query: `4. What is your PostgreSQL connection string? (default: ${defaults.POSTGRES_URL}): `
  }
];

const answers = {};

function ask(index) {
  if (index >= questions.length) {
    writeEnv();
    return;
  }

  const q = questions[index];
  rl.question(q.query, (answer) => {
    answers[q.key] = answer.trim() || defaults[q.key];
    ask(index + 1);
  });
}

function writeEnv() {
  rl.close();
  const envContent = `# ──────────────────────────────────────────────────────────
# SIDERIS Environment Settings (Generated by Setup Script)
# ──────────────────────────────────────────────────────────

# The target web application to protect
TARGET_URL=${answers.TARGET_URL}

# The port where public users access your site
PROXY_PORT=${answers.PROXY_PORT}

# Internal ports and endpoints
INGEST_PORT=5000
DASHBOARD_PORT=6001
INGEST_HOST=http://localhost:5000

# Backend databases
REDIS_URL=${answers.REDIS_URL}
POSTGRES_URL=${answers.POSTGRES_URL}
`;

  const envPath = path.resolve(__dirname, '../.env');
  fs.writeFileSync(envPath, envContent);

  console.log('\n==================================================');
  console.log('🎉 SIDERIS Setup Configuration Complete!');
  console.log('==================================================');
  console.log(`Saved configuration to: ${envPath}\n`);
  console.log('To start SIDERIS using Docker, run:');
  console.log('👉 docker compose up -d');
  console.log('\nThen access your website via the Sideris WAF Proxy at:');
  console.log(`🔗 http://localhost:${answers.PROXY_PORT}`);
  console.log('==================================================\n');
}

console.log('==================================================');
console.log('🛡️  SIDERIS Runtime Defense — Interactive Installer');
console.log('==================================================\n');
ask(0);
